<?php
	$this->headScript()->appendFile($this->basePath() . '/js/people.js');
?>
<meta name="google-signin-client_id" content="">

<div class="container" id="content">
	<div class="page-header">
		<h1>People</h1>
	</div>
	<ol id="people" style="font-size: 150%">

	</ol>
</div>
<script>
function onLoad() {
	gapi.load('auth2', function() {
    gapi.auth2.init();
	});
}
</script>
<script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>