<?php
$this->headScript ()->appendFile ( $this->basePath () . '/js/profile.js' );
?>
<div class="container" id="content">
	<div class="page-header">
		<h1>User Profile Page</h1>
	</div>
	<div id="profile-content"
		user-id="<?php echo $this->layout()->getVariable('user');?>"
		org-id="<?php echo $this->layout()->getVariable('organization')->getId();?>">
		<div class="row">
			<div id="user-info" class="col-md-6	">
				<div class="row">
					<div>
						<img id="photo" class="img-thumbnail img-responsive" src=""
							alt="User Profile Photo"
							style="margin-left: 50px; max-height: 200px;">
					</div>
					<h3 id="name"></h3>
					<p id="birthday"></p>
					<address id="email"></address>
					<p id="description"></p>
				</div>
				<div class="row">
					<h2>Skills</h2>
					<p>No Skill available</p>
				</div>
			</div>
			<div id="other-info" class="col-md-6">
				<div class="row">
					<h1 id="orgName"></h1>
					<h4 id="orgMembership"></h4>
				</div>
				<div class="row">
					<h2>Credits</h2>
					<table class="table" >
						<caption>Generated credits</caption>
						<thead>
							<tr>
								<th class="text-center">Organization</th>
								<th class="text-center">Tot. Generated Credits</th>
								<th class="text-center">Available Credits</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td id="tdOrg" class="text-center"></td>
								<td id="tdTotal" class="text-center"></td>
								<td id="tdAvailable" class="text-center"></td>
							</tr>
						</tbody>
					</table>
					<hr>
					<table class="table">
						<caption>Credit Account History</caption>
						<thead>
							<tr>
								<th class="text-center">Last 3 months</th>
								<th class="text-center">Last 6 months</th>
								<th class="text-center">Last Year</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td id="tdLast3Month" class="text-center"></td>
								<td id="tdLast6Month" class="text-center"></td>
								<td id="tdLastYear" class="text-center"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
					<h2>Tasks</h2>
			</div>
			<div class="row">
				<form class="form-horizontal" id="tasksFilter">
					<div class="form-group">
						<label for="inputFrom" class="col-lg-1 control-label">From</label>
						<div class="col-lg-2">
							<input type="text" class="form-control" id="inputFrom" placeholder="gg/mm/aaaa">
						</div>
						<label for="inputTo" class="col-lg-1 control-label">To</label>
						<div class="col-lg-2">
							<input type="text" class="form-control" id="inputTo" placeholder="gg/mm/aaaa">
						</div>
						<div class="col-lg-2">
							<button type="submit" class="btn btn-primary btn-sm">Filter</button>
						</div>
					</div>
				</form>
			</div>
			<div id="task-metrics"></div>
		</div>
	</div>
</div>
<script>
function onLoad() {
	gapi.load('auth2', function() {
    gapi.auth2.init();
	});
}
</script>
<script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
