language: php

php:
  - 5.5
  - 5.4
  - hhvm

before_script:
  # Set the GitHub OAuth token to make use of the 5000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer install -d src

script:
  - phpunit --configuration tests/phpunit.xml
  - ./bin/behat --config tests/behat.yml
