language: php

php:
  - 5.6
  - 5.5

env:
  - APPLICATION_ENV=acceptance

addons:
  hosts:
    - ora.local
    - oraprojecttest

install:
  - composer self-update

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # configure apache virtual hosts
  - sudo sed --in-line 's/${ENVVAR}/'"$ENVVAR"'/g' /etc/apache2/conf.d/env.conf
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
    # Set the GitHub OAuth token to make use of the 5000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer install -d src --dev
  - mysql -e 'create database oraproject_test;'
  - src/vendor/bin/doctrine-module orm:schema-tool:create
  - mysql oraproject_test < tests/sql/init.sql

script:
  - cd tests/unit
  - phpunit
  - cd ../integration
  - phpunit
  - cd ..
  - ../src/vendor/bin/behat
