<div class="container">
	<div class="row" style="margin-top: 10px">
		<div class="jumbotron col-md-8">
			<h2 class="text-center zf-green">O.R.A. Project Mail Test</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">
						<strong>O.R.A. Project Mail - Plain Text</strong>
					</h3>
				</div>
				<div class="panel-body">
					
					<p>This is plain text mail.</p>
					<p><a id='sendMail_1' class="btn btn-success pull-right" href="/mail/mail-simple">Send Mail</a></p>
				</div>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">
						<strong>O.R.A. Project Mail - Template 1</strong>
					</h3>
				</div>
				<div class="panel-body">
					<h4>Benvenuto!!</h4>
					<p>
						Salve <b><?php echo $this->placeholder_User?></b>,
					</p>
					<p>grazie per aver completato la registrazione al progetto O.R.A.</p>
					<hr>

					<p align="right">
						<b>O.R.A. Project Mail Sender</b>
					</p>
					<p><a id='sendMail_2' class="btn btn-success pull-right" href="/mail/mail-login">Send Mail</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">
						<strong>O.R.A. Project Mail - Template 2</strong>
					</h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">
							<p>Lorem ipsum dolor sit amet, <b><?php echo $this->placeholder?></b> consectetur adipiscing elit. In id
								suscipit quam. Nunc ultrices sollicitudin varius. Morbi rutrum
								maximus sem, sit amet <b><?php echo $this->placeholder?></b> dui maximus quis.</p>
						</div>
					</div>
					<div class="row" style="margin-top: 10px; margin-bottom: 10px;">
						<div class="col-md-8 col-md-offset-1 panel panel-primary">
							<div class="panel-heading">
								<strong><?php echo $this->taskUser?></strong> ha modificato l'item "<b><?php echo $this->taskTitle?></b>" <span
									class="badge pull-right"><b><?php echo $this->taskId?></b></span>
							</div>
							<div class="panel-body"><?php echo $this->taskDetail_1?></div>
							<div class="panel-body"><?php echo $this->taskDetail_2?></div>
							
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<p>Sed nec elit a nulla placerat elementum. In a felis vel leo
								scelerisque dapibus.</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<hr>
							<p align="right">
								<b>O.R.A. Project Mail Sender</b>
							</p>
							<p><a id='sendMail_3' class="btn btn-success pull-right" href="/mail/mail-task">Send Mail</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


</div>
