<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
	<b><?= $this->organization->getName() ?></b> has a new member! <strong><?= $this->member->getFirstname() ?> <?= $this->member->getLastname() ?></strong> just joined the organization.</p>
<p>Don't miss the chance to send her / him your welcome message :-)</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are an administrator of the "<?= $this->organization->getName() ?>" organization.</p>