<?php if($this->identity() != null) { ?>
<div id="createStreamModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createStreamLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
				
			<form action="<?php echo $this->url('streams', array('orgId'=>$this->layout()->getVariable('organization')->getId()));?>">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">&times;</span>
					<span class="sr-only">Close</span>
				</button>
				<h4 class="modal-title">New Stream</h4>
			</div>
			<div class="modal-body">
				<div class="alert" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
				</div>				
				<div class="form-group">
					<label for="subject">Subject</label>
					<input type="text" class="form-control" id="subject" required name="subject">
				</div>				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-primary">Submit</button>
			</div>
			</form>
		</div>
	</div>
</div>
<?php } ?>