<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('O.R.A.') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/auth.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <!-- In page styles -->
        <?php echo $this->headStyle(); ?>
    </head>
    
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('O.R.A.') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('tasks-home') ?>"><?php echo $this->translate('Items') ?></a></li>
                        <li><a href="<?php echo $this->url('accounting-home') ?>"><?php echo $this->translate('Credits') ?></a></li>
                        <li><a href=""><?php echo $this->translate('Decisions') ?></a></li>
                        <li><a href="<?php echo $this->url('people-home') ?>"><?php echo $this->translate('People') ?></a></li>
					</ul>
					<?php echo $this->UserBoxHelper(); ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php             
            echo $this->content; 
            
            echo $this->LoginPopupHelper(); 
            ?>
            <hr>
            <footer>
            </footer>
        </div> <!-- /container -->
    
        <?php echo $this->inlineScript() ?>
                  
    </body>        
</html>
