<?php $this->headScript()->appendFile($this->basePath() . '/js/accounting.js'); ?>
<div class="container">
	<div class="page-header">
		<h1>Credits</h1>
	</div>
	<ul id="accounts"></ul>
	
	<table class="table" id="transactions-container">
		<caption><h3>Transactions</h3></caption>
		<thead>
			<tr>
				<td colspan="3" style="text-align: right; font-weight: bold">Actual Balance</td>
				<td id="actual-balance"></td>
			</tr>
			<tr>
				<th>Date</th>
				<th>Description</th>
				<th>Ref.</th>
				<th>Amount</th>
			</tr>
		</thead>
		<tbody id="transactions">
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="3" style="text-align: right; font-weight: bold">Initial balance</td>
				<td id="starting-balance"></td>
			</tr>
		</tfoot>
	</table>
</div>
<div class="modal fade" id="depositModal" tabindex="-1" role="dialog" aria-labelledby="depositModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form method="POST" action="">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="depositModalLabel">Deposit</h4>
				</div>
				<div class="modal-body">
					<div class="alert" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="form-group">
						<label for="amount">Credits</label>
						<input type="number" name="amount" id="amount" class="form-control" required="required"/>
					</div>
					<div class="form-group">
						<label for="description">Description</label>
						<input type="text" name="description" id="description" class="form-control"/>
					</div>
					</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
			</form>
		</div>
	</div>
</div>