<div class="modal fade" id="incomingTransferModal" tabindex="-1" role="dialog" aria-labelledby="incomingTransferModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form method="POST" action="">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="incomingTransferModalLabel">Incoming Transfer</h4>
				</div>
				<div class="modal-body">
					<div class="alert" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="form-group">
						<label for="payer">Payer e-mail</label>
						<input type="email" name="payer" id="payer" class="form-control" required="required"/>
					</div>
					<div class="form-group">
						<label for="amount">Credits</label>
						<input type="number" name="amount" id="amount" class="form-control" required="required" min="0"/>
					</div>
					<div class="form-group">
						<label for="description">Description</label>
						<input type="text" name="description" id="description" class="form-control" maxlength="256" placeholder="Why are you transferring credits from the payer?"/>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
			</form>
		</div>
	</div>
</div>