<p>Hi <?=$this->recipient->getFirstname()?>,<br>
	it seems the kanbanize board connected to your organization "<?=$this->organization->getName()?>" was modified. Please check the organization settings and restore the columns name on Kanbanze accordingly.
</p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are a member of the "<?= $this->organization->getName() ?>" organization.</p>