<div class="jumbotron">
    <center><h1><span class="zf-green">O.R.A. Project Home Page</span></h1></center>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Task management</h3>
            </div>
            <div class="panel-body">
                <p><ul>
                    <li>List of available tasks</li>
                    <li>Create a new task</li>
                </ul></p>
                <p><a id='listAvailableTask' class="btn btn-success pull-right">List available tasks &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">List of task to test Kanbanize Acceptance</h3>
            </div>
            <div class="panel-body">
                <p><ul>
                    <li>List of acceptableTask</li>
                    <li>Accept Task</li>
                </ul></p>
                <p><a id='acceptanceTask' class="btn btn-success pull-right" href="kanbanize/list">Start Test &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Lorem ipsum</h3>
            </div>
            <div class="panel-body">
                <p><ul>
                    <li>Lorem ipsum</li>
                    <li>Lorem ipsum</li>
                </ul></p>
                <p><a class="btn btn-default disabled pull-right" href="#">Disabled button &raquo;</a></p>
            </div>
        </div>
    </div>
</div>