<div class="modal fade" id="assignSharesModal" tabindex="-1" role="dialog" aria-labelledby="assignSharesModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="" class="form-horizontal" onsubmit="return confirm('Are you sure?')">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class='sr-only'>Close</span></button>
					<h4 class="modal-title">Assign shares</h4>
				</div>
				<div class="modal-body">
					<div class="alert" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div id="assignSharesMembers"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-warning" data-action="skipAssignShares">Skip</button>
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
			</form>
		</div>
	</div>
</div>
