<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createTaskModalLabel" aria-hidden="true" id="createTaskModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Create new task</h4>
				</div>
				<div class="modal-body">
					<div class="alert" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="form-group">
						<label for="subject">Subject</label>
						<input type="text" name="subject" class="form-control" required="required">
					</div>
					<div class="form-group"> 
						<label for="createTaskStreamID">Stream</label>
						<select name="streamID" class="form-control" required="required" id="createTaskStreamID">
							<option value=""></option>
						</select>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Create</button>
				</div>
			</form>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>