<div class="modal fade" id="estimateTaskModal" tabindex="-1" role="dialog" aria-labelledby="estimateTaskModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class='sr-only'>Close</span></button>
					<h4 class="modal-title">Estimate the task</h4>
				</div>
				<div class="modal-body">
					<div class="alert" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="form-group">
						<label for="estimateTaskCredits">Credits</label>
						<input type="number" id="estimateTaskCredits" pattern="/^[+]?([0-9]+(?:[\.][0-9]*)?|\.[0-9]+)$/" class="form-control" name="value">
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-warning" id="skipEstimateTask">Skip</button>
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
			</form>
		</div>
	</div>
</div>