<?php
	$this->headScript()->appendFile($this->basePath() . '/js/task-management.js');
	$this->headStyle()->appendStyle('ul.task-details { list-style: none; margin:0; padding: 0; }');
	$this->headStyle()->appendStyle('ul.task-actions { list-style: none; margin:0; padding: 0; }');
	$this->headStyle()->appendStyle('ul.task-actions li { display: inline-block; }');
	$this->headStyle()->appendStyle('.panel-heading a { cursor: pointer; }');
	?>
<div style="position: fixed; bottom: 2em; right: 2em">
	<a class="btn btn-primary btn-fab btn-raised mdi-content-add" style="display:none" data-toggle="modal" data-target="#createTaskModal" id="createTaskBtn"></a>
</div>
<div class="container" id="content">
	<div class="page-header">
		<h1>Items</h1>
	</div>
	<div class="alert" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		  <span aria-hidden="true">&times;</span>
		</button>
	</div>
	<ul id="tasks" style="list-style: none; padding: 0; margin: 0">
	</ul>
</div>
<?php echo $this->partial('task-management/index/create-task-modal.phtml') ?>
<?php echo $this->partial('task-management/index/edit-task-modal.phtml') ?>
<?php echo $this->partial('task-management/index/estimate-task-modal.phtml') ?>
<?php echo $this->partial('task-management/index/assign-shares-modal.phtml') ?>
<?php echo $this->partial('task-management/index/task-detail-modal.phtml') ?>
<?php echo $this->partial('task-management/index/create-stream-modal.phtml') ?>