<div class="container"><p>
<?php

	if(isset($this->error))
	{
		switch($this->error)
		{
			case 'Auth.InvalidCode': 
									echo "InvalidCode";
									break;
			case 'Auth.InvalidProvider': 
									echo "Provider not valid";
									break;
			case 'Auth.InvalidToken': 
									echo "Token not valid";
									break;
			default:
				echo $this->error;
		}
	}	
	elseif(!$this->authenticate->isValid())
	{ 
		switch ($this->authenticate->getCode()) {
				
			case \Zend\Authentication\Result::FAILURE_IDENTITY_NOT_FOUND:
				echo "Identity not found";
				break;
		
			case \Zend\Authentication\Result::FAILURE_CREDENTIAL_INVALID:
				echo "Credential invalid";
				break;
		
			default:
				echo "Internal error";
				break;
		}
	} 
?>
</p></div>