<p>Hi <?= $this->recipient->getFirstname()." ".$this->recipient->getLastname()?>,<br>
The item <b><?= $this->task->getSubject()?></b> is still on OnGoing status!</p>
<p>Please follow <a href="<?= $this->url('tasks-home',array('orgId' => $this->task->getStream()->getOrganization()->getId()), array('force_canonical' => true))?>"> this link</a> and add your estimation as soon as possible.</p>
<br/> 
<p>Thank you!</p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are member of the "<?= $this->task->getSubject() ?>" item.</p>		