<p>Hi <?= $this->recipient->getFirstname() ?>,<p>
<p>You haven't estimated the item <b><?= $this->task->getSubject()?></b> yet!</p>
<p>It is important you do it as soon as possible to define with your taskmate the value of the item.</p>
<p>Please follow <a href="<?= $this->host . $this->url('collaboration-home', ['orgId' => $this->task->getOrganizationId(), 'id' => $this->task->getId()])?>"> this link</a> and add your estimation as soon as possible.</p>
<br/> 
<p>Thank you!</p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are member of the "<?= $this->task->getSubject() ?>" item.</p>		