<p>Hi <?php echo $this->name?>,</p>
<p><b>the time</b> available to assign shares to the item "<?php echo $this->taskSubject?>" <b>is running out!</b></p> 
<p>It is important you won't miss the chance to tell your taskmates what you think about the team contribution.</p> 
<p>Follow <a href="<?php echo $this->url?>">this link</a> to do it as soon as possible</p>
<br/> 
<p>Thank you!</p>
<p>;)</p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are member of the "<?= $this->taskSubject ?>" item.</p>		
