<p>Hi <?php echo $this->recipient->getFirstname()?>,<br>
	<b><?= $this->task->getSubject()?></b> has an important update! <b><?php echo $this->member->getFirstname()?> <?php echo $this->member->getLastname()?></b> just assigned her / his shares to item members.</p>
<p>Check the item shares assignment progress online.</p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are an owner of the "<?= $this->task->getSubject() ?>" item.</p>