<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
the item you contributed to "<?= $this->task->getSubject()?>" has been accepted!</p>
<p>It's time to <a href="<?= $this->host . $this->url('collaboration-home', ['orgId' => $this->task->getOrganizationId(), 'id' => $this->task->getId()]) ?>">assign your shares</a> to the members of this item.</p>
<p>Don't forget it! Do it right now!</p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are member of the "<?= $this->task->getSubject() ?>" item.</p>
