<p>Hi <?= $this->recipient->getFirstname() ?>,</p>
<p><b>the time</b> available to assign shares to the item "<?= $this->task->getSubject()?>" <b>is over!</b></p> 
<p>This task has been automatically closed.</p> 
<p>Follow <a href="<?= $this->host . $this->url('collaboration-home', ['orgId' => $this->task->getOrganizationId(), 'id' => $this->task->getId()]) ?>"> this link</a> to find out shares calculations</p>
<br/> 
<p>Thank you!</p>
<p>;)</p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are member of the "<?= $this->task->getSubject() ?>" item.</p>
