<p>Hi <?= $this->recipient->getFirstname() ?>,</p>
<p>the item "<?= $this->task->getSubject()?>" <b>has been accepted!</b></p> 
<p>It's time to <b>assign shares</b> to this item.</p> 
<p>Follow <a href="<?= $this->host . $this->url('collaboration-home', ['orgId' => $this->task->getOrganizationId(), 'id' => $this->task->getId()]) ?>"> this link</a> to do it as soon as possible</p>
<br/> 
<p>Thank you!</p>
<p>;)</p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are member of the "<?= $this->task->getSubject() ?>" item.</p>
