<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
the item you contributed to "<?= $this->task->getSubject()?>" has been closed!</p>
<p>The credits you gained have been transferred into <a href="<?= $this->host . $this->url('collaboration-home', ['orgId' => $this->task->getOrganizationId(), 'id' => $this->task->getId()]) ?>">your account</a>.</p>
<p>Thank you for contributing and keep on doing it!</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are member of the "<?= $this->task->getSubject() ?>" item.</p>
