<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
a new work item idea has been accepted  in  "<?= $this->stream->getSubject()?>" stream: <b><?= $this->task->getSubject()?></b>.</p>
<p><a href="<?= $this->host . $this->url('collaboration-home', ['orgId' => $this->task->getOrganizationId(), 'id' => $this->task->getId()]) ?>">Check the details here</a></p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are a member of the "<?= $this->organization->getName() ?>" organization.</p>
