<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
<?php if(is_null($this->member)) {
	echo 'an organization member';
} else {
	echo '<b>'.$this->member->getFirstname().' '.$this->member->getLastname().'</b>';
}?> proposed a new work item idea into the "<?= $this->stream->getSubject()?>" stream: <b><?= $this->task->getSubject()?></b>.</p>
<p><a href="<?= $this->host . $this->url('collaboration-home', ['orgId' => $this->task->getOrganizationId(), 'id' => $this->task->getId()]) ?>">Check it out and vote for accepting or rejecting it!</a></p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are a member of the "<?= $this->organization->getName() ?>" organization.</p>
