<p>Hi <?= $this->recipient->getFirstname() ?> <?= $this->recipient->getLastname()?>,<br>
the  <?= $this->stream->getSubject()?> stream has a new work item idea proposed by <?= $this->member->getFirstname()?> <?= $this->member->getLastname()?>: <b><?= $this->task->getSubject()?></b>.</p>
<p>Check it out!</p>
<p>O.R.A.</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are a member of the "<?= $this->organization->getName() ?>" organization.</p>
