<?php

use Ora\Kanbanize\KanbanizeTask;
?>

<div class="page-header">
	<h1>Task List</h1>
	<small>Example page for the function task acceptance</small>
</div>

<?php echo $this->flashMessenger()
			->setMessageOpenFormat('<div class="well panel-success"><p>')
			->setMessageSeparatorString('</p><p>')
			->setMessageCloseString('</p></div>')
			->render('success'); 
	echo $this->flashMessenger()
			->setMessageOpenFormat('<div%s class="well panel-error"><p>')
			->setMessageSeparatorString('</p><p>')
			->setMessageCloseString('</p></div>')
			->render('error');?>
<div class="container">
	<table class="table table-responsive table-striped">
		<thead>
			<tr>
				<th>id</th>
				<th>Subject</th>
				<th>Status</th>
				<th colspan="2">Action</th>
			</tr>
		</thead>
		<tbody>
		<?php
		
		foreach ( $tasks as $singletask ) {
			?>
<tr>
				
 	<td> <?php echo $singletask->getId();?> </td>
 
				
 	<td> <?php echo $singletask->getSubject();?> </td>
 
				
    <td> <?php echo KanbanizeTask::getMappedStatus($singletask->getStatus());?> </td>
 
	<td>
	<?php if(in_array($singletask->getId(), $acceptable)){?>
	<a href="/kanbanize/task/<?php echo $singletask->getId();?>/client/test?method=accept">
	<button class="btn btn-primary" id ="<?php echo $singletask->getId();?>">Accept</button>
	</a>
	<?php }?>
	</td>
	<td>
	<?php if(in_array($singletask->getId(), $back2ongoing)){?>
	<a href="/kanbanize/task/<?php echo $singletask->getId();?>/client/test?method=ongoing">
	<button class="btn btn-primary" id ="<?php echo $singletask->getId();?>">Back to ongoing</button>
	</a>
	<?php }?>
	</td>
				
</tr>

<?php
}
?>
		</tbody>
	</table>
</div>