<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
		<?php echo is_null($this->organization) ? $this->headTitle('O.R.A.') : $this->headTitle($this->translate($this->organization->getName()));?>

<?php echo $this->headMeta()
	->appendName('viewport', 'width=device-width, initial-scale=1.0')
	->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- Le styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
	->prependStylesheet($this->basePath() . '/css/style.css')
	->prependStylesheet($this->basePath() . '/css/bootstrap-social.css')
	->prependStylesheet($this->basePath() . '/css/material-wfont.min.css')
	->prependStylesheet($this->basePath() . '/css/ripples.min.css')
	->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
	->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css') ?>

<!-- Scripts -->
<?php echo $this->headScript()
	->prependFile($this->basePath() . '/js/organizations.js')
	->prependFile($this->basePath() . '/js/material.min.js')
	->prependFile($this->basePath() . '/js/ripples.min.js')
	->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js')
	->prependFile('https://code.jquery.com/jquery-2.1.3.min.js')
	->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
	->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
; ?>
<!-- In page styles -->
<?php echo $this->headStyle(); ?>
<script>
	$(document).ready(function() {
		$.material.init();
	});
</script>
</head>

<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
				</button>
				<?php if($this->organization) { ?>
					<a href="<?php echo $this->url('home') ?>" class="navbar-brand">
						<span class="mdi-navigation-chevron-left"></span>
						<?= $this->translate($this->organization->getName()) ?>
					</a>
					<?php } else {?>
						<a class="navbar-brand" href="#">O.R.A.</a>
					<?php } ?>
			</div>
			
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav" id="firstLevelMenu" role="menu">
				<?php if($this->organization){?>
					<li><a id="tasks-home" href="<?php echo $this->url('tasks-home', array('orgId'=>$this->organization->getId())); ?>"><?php echo $this->translate('Items') ?></a></li>
					<li><a id="accounting-home" href="<?php echo $this->url('accounting-home', array('orgId'=>$this->organization->getId())); ?>"><?php echo $this->translate('Credits') ?></a></li>
					<li><a id="decisions-home" href=""><?php echo $this->translate('Decisions') ?></a></li>
					<li><a id="people-home"href="<?php echo $this->url('people-home', array('orgId'=>$this->organization->getId())); ?>"><?php echo $this->translate('People') ?></a></li>
					<?php }?>
				</ul>
				<ul class="nav navbar-nav navbar-right" id="identityMenu" style="display: none">
					<li><a href="#"></a></li>
					<li><a href="#" onclick="signOut();">Logout</a></li>
				</ul>
				<script>
					function signOut() {
						var auth2 = gapi.auth2.getAuthInstance();
						auth2.signOut().then(function () {
							console.log('User signed out.');
							$('div#sign-in').trigger('loggedOut');
						});
					}
				</script>
			</div><!--/.nav-collapse -->
		</div>
	</nav>
		<?php echo $this->content; ?>
		<?php echo $this->partial('people/create-organization-modal.phtml') ?>
		<?php echo $this->inlineScript() ?>
	</body>
</html>
