<?php if($this->identity() != null) {?>
<div class="col-md-4 col-md-offset-4">
	<div class="panel panel-default"
		style="box-shadow: none; background-color: transparent;">
		<div class="panel-heading" style="background-color: transparent;">
			<h3 class="panel-title text-center">Please choose one of your
				organizations</h3>
		</div>
		<div class="panel-body" id="organizations_body">
			<div class="progress" id="wait_for_organizations"
				style="height: inherit;">
				<div class="progress-bar progress-bar-striped active"
					role="progressbar" style="width: 100%;">Loading...</div>
			</div>
		</div>
		<div class="panel-footer" style="background-color: transparent;">
			<button class="btn btn-primary" data-toggle="modal"
				data-target="#createOrganizationModal" type="button">Create new
				Organization</button>
			<a class="btn btn-info" href="organizations" role="button">Join an
				organization »</a>
		</div>
	</div>
</div>

<?php
}
?>
