<html>
	<head>
		<title><?php echo $this->title?></title>
	</head>
	<body>
	
		<p>Hi <?php echo $this->name?>,</p>
		<p><b>the time</b> available to assign shares to the task "<?php echo $this->taskSubject?>" <b>is running out!</b></p> 
		<p>It is important you won't miss the chance to tell your taskmates what you think about the team contribution.</p> 
		<p>Follow <a href="<?php echo $this->url('tasks-home')."#".$this->taskId;?>">this link</a> to do it as soon as possible:</p><br/> 
		<br/>

		<p>Thank you!</p>
		<p>;)</p>
		
	</body>
</html>