<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Kanbanize\Module'                        => __DIR__ . '/Module.php',
    'Kanbanize\Controller\KanbanizeController' => __DIR__ . '/src/Kanbanize/Controller/KanbanizeController.php',
    'Kanbanize\Controller\TestKanbanizeActionController' => __DIR__ . '/src/Kanbanize/Controller/TestKanbanizeActionController.php',
    'KanbanizeTest\Framework\TestCase'        => __DIR__ . '/tests/Kanbanize/Framework/TestCase.php',
    'KanbanizeTest\SampleTest'                => __DIR__ . '/tests/Kanbanize/SampleTest.php',
);
