<h2>Platform stats</h2>
<table style="text-align:left">
    <tr>
        <th>Organizations:</th>
        <td><?= $this->stats['orgs']; ?></td>
    </tr>
    <tr>
        <th>Tasks:</th>
        <td><?= $this->stats['tasks']; ?></td>
    </tr>
    <tr>
        <th>Users:</th>
        <td><?= $this->stats['users']; ?></td>
    </tr>
    <tr>
        <th>Kanbanize connected boards:</th>
        <td><?= $this->stats['kanbanize']; ?></td>
    </tr>
</table>
