<?php 

	if($this->login['valid'] === false)
	{ 
?>

<div class="row">

        <div class="col-lg-12">
          <h4>Error!</h4>
          <p><a href="javascript:window.history.back(); ">Torna indietro</a></p>
        </div>
       
</div>

	<?php 
		foreach($this->login['messages'] as $message)
		{
	?>
		<div class="row">
					
		     <div class="col-lg-12">
		         <p><?php echo $message; ?></p>
		     </div>
				        
		</div>
	<?php 
		}
	?>
<?php
	} 
	else 
	{
?>

	<div class="row">	
	        <div class="col-lg-12">
	          <h4>Welcome!</h4>	          
	        </div>
	</div>
	
<script type="text/javascript">

	$(document).ready(function() 
				{
					if(opener != null)
					{
						opener.location.reload(true);
						self.close();
					}
	})

</script>


<?php 
	}
?>

