<?php $this->headMeta()
	->appendName('google-signin-scope', 'profile email')
	->appendName('google-signin-client_id', $this->providers['google']->getOptions()->getClientId()); ?>
<?php
$this->headScript()->setAllowArbitraryAttributes(true);
$this->headScript()
	->appendFile('https://apis.google.com/js/platform.js?onload=renderButton', 'text/javascript', [
		'async' => 'async',
		'defer' => 'defer'
	]); ?>

<div class="container">
	<div id="sign-in" class="center-block" style="max-width: 230px; text-align: center">
		<h1>O.R.A.</h1>
		<div id="g-signin2"></div>
		<script>
			function onSuccess(googleUser) {
				var id_token = googleUser.getAuthResponse().id_token;
				console.log("ID Token: " + id_token);

				// Useful data for your client-side scripts:
				var profile = googleUser.getBasicProfile();
				$('div#sign-in').trigger('loggedIn', {
					token:  id_token,
					name:   profile.getName(),
					avatar: profile.getImageUrl(),
					email:  profile.getEmail()
				});
			};
			function onFailure(error) {
				console.log(error);
			}
			function renderButton() {
				gapi.signin2.render('g-signin2', {
					'width': 230,
					'longtitle': true,
					'theme': 'dark',
					'onsuccess': onSuccess,
					'onfailure': onFailure
				});
			}
		</script>
	</div>
	<div id="organizations" style="display:none; max-width: 250px; text-align: center" class="center-block">
		<h1>Choose an organization</h1>
		<ul style="text-align: left;"></ul>
		<ul style="margin-left:0; padding-left:0; list-style: none">
			<li><button class="btn btn-primary" data-toggle="modal" data-target="#createOrganizationModal" type="button">New Organization</button></li>
			<li><a class="btn btn-info" href="/organizations" role="button">Join Organization</a></li>
		</ul>
	</div>
</div>
