<div class="container">

	<div class="row" style="margin-top: 40px">
	
	<?php if(!$this->identity()){?>    
	    <div class="col-md-4 col-md-offset-4">
			<div class="panel panel-default"
				style="box-shadow: none; background-color: transparent;">
				<div class="panel-heading" style="background-color: transparent;">
					<h3 class="panel-title text-center">Sign in into O.R.A.</h3>
				</div>
				<div class="panel-body">
	                <?php echo $this->LoginHelper();?>
	            </div>
			</div>
		</div>
	<?php }?>
	
	<?php
	
echo $this->partial ( 'layout/organizations-box.phtml', array (
			'identity' => is_null ( $this->identity () ) ? null : $this->identity ()['user'] 
	) );
	?>
	
	
	</div>
</div>
