<?php $this->headMeta()
	->appendName('google-signin-scope', 'profile email')
	->appendName('google-signin-client_id', $this->providers['google']->getOptions()->getClientId()); ?>
<?php
$this->headScript()->setAllowArbitraryAttributes(true);
$this->headScript()
	->appendFile('https://apis.google.com/js/platform.js', 'text/javascript', [
		'async' => 'async',
		'defer' => 'defer'
	]); ?>

<div class="container">

	<div class="row" style="margin-top: 40px">
	
	<?php if(!$this->identity()){?>    
	    <div class="col-md-4 col-md-offset-4">
			<div class="panel panel-default"
				style="box-shadow: none; background-color: transparent;">
				<div class="panel-heading" style="background-color: transparent;">
					<h3 class="panel-title text-center">Sign in into O.R.A.</h3>
				</div>
				<div class="panel-body">
	                <?php echo $this->LoginHelper();?>
	            </div>
			</div>
		</div>
	<?php }?>
	
	<?= $this->partial('layout/organizations-box.phtml')?>
	</div>
	<div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div>
	<script>
		function onSignIn(googleUser) {
			var id_token = googleUser.getAuthResponse().id_token;
			console.log("ID Token: " + id_token);

			var xhr = new XMLHttpRequest();
			xhr.open('GET', 'http://oraproject.org/auth/google');
			xhr.setRequestHeader('GOOGLE-JWT', id_token);
			xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
			xhr.onload = function() {
				console.log('Signed in as: ' + xhr.responseText);
			};
			xhr.send('idtoken=' + id_token);

			// Useful data for your client-side scripts:
			var profile = googleUser.getBasicProfile();
			console.log("ID: " + profile.getId()); // Don't send this directly to your server!
			console.log("Name: " + profile.getName());
			console.log("Image URL: " + profile.getImageUrl());
			console.log("Email: " + profile.getEmail());
		};
	</script>
</span>
</div>
